version: 2
jobs:
  build:
    macos:
      xcode: "11.3.1"
    steps:
      - checkout
      - run:
          name: Fetch submodules
          command: git submodule update --init --recursive -j 16
      - run:
          name: Install dependency tools
          command: |
            brew install cmake
      - run:
          name: Build opencv
          command: |
            mkdir out
            python platforms/ios/build_framework.py --contrib opencv_contrib --iphoneos_archs arm64 --iphonesimulator_archs x86_64 out
            zip --symlinks -r opencv_ios_framework.zip out/opencv2.framework
            zip --symlinks -r opencv_ios_build_data.zip out/build
      - store_artifacts:
          path: opencv_ios_framework.zip
          destination: ios_framework
      - store_artifacts:
          path: opencv_ios_build_data.zip
          destination: build-data
